site_name: ElfHosted - app hosting that works like magic! 🪄
# site_description: app hosting that magically "Just Works(tm)"
site_author: 'David Young'
site_url: 'https://elfhosted.com'
edit_uri: 'edit/main/docs/'


# Fail to build if we have broken links
# strict: true

# Copyright
copyright: 'Copyright &copy; 2023 David Young, Funky Penguin Limited'

# Repository
repo_name: 'elfhosted-docs'
repo_url: 'https://github.com/geek-cookbook/elfhosted-docs'


# Plugins
plugins:
  search:
  minify:
    minify_html: true
  autolinks:
  git-revision-date-localized:
    type: date
    fallback_to_build_date: true  
  macros:
    verbose: true
    include_dir: _includes
  meta-descriptions: # If not provided, auto-generate a description (https://pypi.org/project/mkdocs-meta-descriptions-plugin/)
  meta:
  blog:
    # post_excerpt: required
    post_url_format: "{date}/{file}" # this allows us to change the post title in future without breaking URLs
  tags:
    tags_file: blog/tags.md
  rss:
    match_path: blog/posts/.*
    date_from_meta:
      as_creation: date
    categories:
      - categories
      - tags
    abstract_chars_count: 200
    image: https://geek-cookbook.funkypenguin.co.nz/images/site-logo.png
    url_parameters:
      utm_source: "geek-cookbook-blog"
      utm_medium: "RSS"
      utm_campaign: "feed-syndication"
  social:
    cards_layout_options:
      font_family: Ubuntu  
    cards_color:
        fill: "#FFFFFF" 
        text: "#000000"  
  privacy:
    external_links_attr_map:
      target: _blank 
      rel: nofollow   
    external_assets_exclude:
      - shields.io/*      
  optimize:
    enabled: false # seems to break netlify builds :(

#theme_dir: mkdocs-material
nav:
  - Home: index.md
  - Apps:
    - app/index.md
    - Audiobookshelf: app/audiobookshelf.md
    - Autobrr: app/autobrr.md
    - Bazarr: app/bazarr.md
    - Calibre: app/calibre.md
    - Calibre Web: app/calibre-web.md
    - Deluge: app/deluge.md
    - ElfBot: app/elfbot.md
    - Emby: app/emby.md
    - Filebrowser: app/filebrowser.md
    - Flaresolverr: app/flaresolverr.md
    - Gotify: app/gotify.md
    - Jellyfin: app/jellyfin.md
    - Jellyfin Accounts: app/jellyfin-accounts.md
    - Jellyseerr: app/jellyseerr.md
    - Kavita: app/kavita.md
    - Komga: app/komga.md
    - Lazy Librarian: app/lazylibrarian.md
    - Lidarr: app/lidarr.md
    - Mattermost: app/mattermost.md
    - Minio: app/minio.md
    - Mylar: app/mylar.md
    - Navidrome: app/navidrome.md
    - NextPVR: app/nextpvr.md
    - Notifiarr: app/notifiarr.md
    - NZBGet: app/nzbget.md
    - NZBHydra: app/nzbhydra.md
    - Ombi: app/ombi.md
    - Overseerr: app/overseerr.md
    - Plex: app/plex.md
    - Privatebin: app/privatebin.md
    - Prowlarr: app/prowlarr.md
    - Pyload: app/pyload.md
    - qBittorrent: app/qbittorrent.md
    - Radarr: app/radarr.md
    - Rapidleech: app/rapidleech.md
    - RClone Browser: app/rclonebrowser.md
    - Readarr: app/readarr.md
    - Resilio Sync: app/resiliosync.md
    - RPDB: app/rpdb.md
    - ruTorrent: app/rutorrent.md
    - SABnzbd: app/sabnzbd.md
    - Seafile: app/seafile.md
    - Shoko: app/shoko.md
    - Sonarr: app/sonarr.md
    - Syncthing: app/syncthing.md
    - Tautulli: app/tautulli.md
    - The Lounge: app/thelounge.md
    - Unpackerr: app/unpackerr.md
    - Uptime Kuma: app/uptimekuma.md
    - Vaultwarden: app/vaultwarden.md
    - xTeVe: app/xteve.md
    - Youtube DL: app/youtubedl.md
  - Legal:
    - legal/index.md
    - Acceptable Use: legal/acceptable-use.md
    - Privacy Policy: legal/privacy-policy.md
    - Terms of Service: legal/terms-of-service.md
    - Refund Policy: legal/refund-policy.md
  - Blog: 
    - blog/index.md
    - Tags: blog/tags.md
  - Store 🛒 :
    - store/index.md
    # - Free Trial: store/free-trial.md
  - Support:
    - how-to/index.md
    - FAQ: how-to/faq.md
    - Migrate: how-to/migrate.md
    - Connect Apps: how-to/connect-apps.md
    - Restoring an Arr: how-to/restoring-arr-app.md    


theme:
  name: 'material'
  custom_dir: 'overrides'
  # logo: fontawesome/solid/hat-wizard
  # favicon: 'images/site-logo.svg'
  features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.instant
      - navigation.sections
      - navigation.indexes
      - navigation.top
      - navigation.pruning
      - search.suggest
      - search.share
      - content.code.annotate
      - content.code.copy
      - header.autohide
      - announce.dismiss
      - toc.follow
  icon:
    repo: 'fontawesome/brands/github'
    tag:
      kubernetes: material/kubernetes
      js: fontawesome/brands/js
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Follow system preferences

    # Toggle light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: 'black'
      accent: 'orange'
      toggle:
        icon: material/brightness-7
        name: Burn my eyes!

    # Toggle dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'black'
      accent: 'orange'
      toggle:
        icon: material/brightness-4
        name: Love my eyes!

  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: 'fontawesome/brands/mastodon'
      link: 'https://so.fnky.nz/@funkypenguin'
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/funkypenguin'
    - icon: 'fontawesome/brands/discord'
      link: 'http://discord.elfhosted.com' 
    - icon: 'simple/matrix'
      link: 'http://matrix.funkypenguin.co.nz' 

extra_css:
  - extras/css/icons.css

extra_javascript:
  # - extras/javascript/plausible.js
  # - extras/javascript/widgetbot.js # uncommented for dev
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - extras/javascript/tablesort.js

# Extensions
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      linenums: true
  - toc:
      permalink: false
      toc_depth: 3 # ignore H4/5/6
  - footnotes
  - pymdownx.critic
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
      base_path: _snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: geek-cookbook
      repo: elfhosted-docs
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true 
  - meta
  - md_in_html


